Второе практическое задание
Yandex-Practicum/android-contacts pull request #19
Opened 2022-09-11 06:57 UTC by biornes

2022-09-11 10:33 UTC, MagicUnderHood requested changes

2022-09-11 10:33 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +public class BaseListDiffCallback<T extends ListDiffInterface> extends DiffUtil.ItemCallback<T>  {
По заданию:  
> Класс BaseListDiffCallback должен быть дженерик-классом с ограничением параметра типа на обязательную реализацию интерфейса ListDiffInterface<>. В качестве параметра типа у интерфейса указывается такое же имя, что и у класса.  

Не хватает у ListDiffInterface ограничения, должно быть: `ListDiffInterface<T>`

2022-09-11 10:33 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +    public T getChangePayload(@NonNull T oldItem, @NonNull T newItem) {
Возвращаемый тип у метода должен быть Object вместо T

2022-09-11 10:33 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/filter/FilterContactTypeAdapter.java
> +            new AsyncDifferConfig.Builder<>(new BaseListDiffCallback()).build()
BaseListDiffCallback требует определить дженерик, в данном случае это FilterContactTypeUi

2022-09-11 10:33 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/main/ContactAdapter.java
> +            new AsyncDifferConfig.Builder<>(new BaseListDiffCallback()).build()
Тут тоже нужно задать дженерик для BaseListDiffCallback

2022-09-11 10:33 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/sort/SortTypeAdapter.java
> +            new AsyncDifferConfig.Builder<>(new BaseListDiffCallback()).build()
И здесь задать дженерик

2022-09-11 12:20 UTC, biornes commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +public class BaseListDiffCallback<T extends ListDiffInterface> extends DiffUtil.ItemCallback<T>  {
Исправил

2022-09-11 12:21 UTC, biornes commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +    public T getChangePayload(@NonNull T oldItem, @NonNull T newItem) {
Исправил

2022-09-11 12:21 UTC, biornes commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/filter/FilterContactTypeAdapter.java
> +            new AsyncDifferConfig.Builder<>(new BaseListDiffCallback()).build()
Исправил

2022-09-11 12:21 UTC, biornes commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/main/ContactAdapter.java
> +            new AsyncDifferConfig.Builder<>(new BaseListDiffCallback()).build()
Исправил

2022-09-11 12:21 UTC, biornes commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/sort/SortTypeAdapter.java
> +            new AsyncDifferConfig.Builder<>(new BaseListDiffCallback()).build()
Исправил

2022-09-11 20:25 UTC, MagicUnderHood requested changes

2022-09-11 20:25 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/filter/FilterContactTypeAdapter.java
> +            new AsyncDifferConfig.Builder<FilterContactTypeUi>(new BaseListDiffCallback()).build()
Почти правильно, но FilterContactTypeUi надо было прописать в угловых скобках у BaseListDiffCallback, а не AsyncDifferConfig.Builder. То есть эта строчка должна превратиться в:  
`new AsyncDifferConfig.Builder<>(new BaseListDiffCallback<FilterContactTypeUi>()).build()`
Об этом есть шаг 4 урока:

> Вместо ListDiffCallback надо лишь указать BaseListDiffCallback<>. Не забудьте указать соответствующее каждому адаптеру имя класса, реализующего интерфейс ListDiffInterface  

соответствующее каждому адаптеру имя класса - в данном адаптере это как раз FilterContactTypeUi

2022-09-11 20:25 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/main/ContactAdapter.java
> +            new AsyncDifferConfig.Builder<ContactUi>(new BaseListDiffCallback()).build()
Здесь тоже ContactUi надо было прописать в угловых скобках у BaseListDiffCallback

2022-09-11 20:25 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/sort/SortTypeAdapter.java
> +            new AsyncDifferConfig.Builder<SortTypeUI>(new BaseListDiffCallback()).build()
Здесь тоже SortTypeUI надо было прописать в угловых скобках у BaseListDiffCallback

2022-09-12 20:40 UTC, MagicUnderHood commented
Теперь всё правильно!

2022-12-23 12:11 UTC, closed without merging