PR from Dmitriy Leonov
Yandex-Practicum/android-contacts pull request #29
Opened 2022-09-18 10:20 UTC by Skankhunt68

2022-09-18 22:30 UTC, MagicUnderHood requested changes

2022-09-18 22:30 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +        return false;
Здесь берем реализацию из старого ListDiffCallback из любого адаптера (она везде одинаковая была)

2022-09-18 22:30 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +    }
Не хватает метода getChangePayload, который был во всех реализациях старого ListDiffCallback в каждом из адаптеров

2022-09-18 22:30 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/filter/FilterContactTypeAdapter.java
> -            new AsyncDifferConfig.Builder<>(new ListDiffCallback()).build()
От старого ListDiffCallback из этого класса можно избавиться

2022-09-18 22:30 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/filter/model/FilterContactTypeUi.java
> +        return (this.hashCode()==filterContactTypeUi.hashCode());
Здесь реализация нужна из метода areItemsTheSame старого ListDiffCallback из адаптера FilterContactTypeAdapter

2022-09-18 22:30 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/main/ContactAdapter.java
> -            new AsyncDifferConfig.Builder<>(new ListDiffCallback()).build()
От старого ListDiffCallback из этого класса можно избавиться

2022-09-18 22:30 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/sort/SortTypeUI.java
> +        return (this.hashCode() == sortTypeUI.hashCode());
Здесь реализация нужна из метода areItemsTheSame старого ListDiffCallback из адаптера SortTypeAdapter

2022-09-19 06:53 UTC, Skankhunt68 commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +        return false;
Странно как это произошло, видимо я где-то ошибся когда ПР делал, реализация была) спасибо, сейчас поправлю)

2022-09-19 14:38 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +        return false;
Бывает)

2022-09-19 14:41 UTC, MagicUnderHood commented
Теперь всё правильно!

2022-12-23 12:10 UTC, closed without merging