Реализованы дженерик-интерфейс и дженерик класс для сортировки
Yandex-Practicum/android-contacts pull request #44
Opened 2022-10-16 11:06 UTC by Jahnta

Спринт 4. Проектная работа №2. Применяем дженерики

2022-10-16 18:23 UTC, MagicUnderHood requested changes

2022-10-16 18:23 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +public class BaseListDiffCallback<T extends ListDiffInterface> extends DiffUtil.ItemCallback<T> {
Здесь ещё не хватает `<T>` у ListDiffInterface, по заданию:  
`обязательную реализацию интерфейса ListDiffInterface<>. В качестве параметра типа у интерфейса указывается такое же имя, что и у класса.`

2022-10-16 18:23 UTC, MagicUnderHood commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +}
Не хватает переопределения метода getChangePayload

2022-10-17 08:17 UTC, Jahnta commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +public class BaseListDiffCallback<T extends ListDiffInterface> extends DiffUtil.ItemCallback<T> {
В свежем коммите внесены правки в реализацию интерфейса ListDiffInterface<>

2022-10-17 08:17 UTC, Jahnta commented on app/src/main/java/ru/yandex/practicum/contacts/presentation/base/BaseListDiffCallback.java
> +}
В свежем коммите добавлено переопределение метода getChangePayload

2022-10-17 18:27 UTC, MagicUnderHood commented
Отлично, все замечания исправлены!

2022-12-23 12:10 UTC, closed without merging